/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type PostQuery = {
    post: ({
        id: string;
        title: string;
        content: string | null;
    }) | null;
};
export type PostQueryVariables = {
    id: string;
};
