/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type UserQuery = {
    user: ({
        name: string;
    }) | null;
};
export type UserQueryVariables = {
    id: string;
};
