/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type PostsQuery = {
    posts: ({
        id: string;
        title: string;
        content: string | null;
    })[];
};
export type PostsQueryVariables = {};
